version: '3.8'
 
services:
  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: custompwd
      MYSQL_DATABASE: widgets
    ports:
      - "6033:3306"
    volumes:
      - ./.datadb:/var/lib/mysql