version: '3.8'
 
services:
  db:
    image: mariadb:11.1
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: custompwd
      MARIADB_DATABASE: widgets
    ports:
      - "3307:3306"
